apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: abiorh-registry
      containers:
      - name: frontend
        image: abiorh/school_management_system_frontend:7
        ports:
        - containerPort: 3000
        command: ["npm", "run", "dev", "--", "--host", "--port", "3000"]
        securityContext:
          capabilities:
            add:
              - NET_RAW

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
